<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.921" timestamp="2025-05-20T12:41:32.199205+02:00" hostname="GTA3"><testcase classname="" name="Python.tests.test_connection" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\fuckheinerkleinehack\Documents\RZGS2\RZGCS\Python\tests\test_connection.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_connection.py:2: in &lt;module&gt;
    from backend.mavlink_connector import MavlinkConnector
E   ImportError: cannot import name 'MavlinkConnector' from 'backend.mavlink_connector' (C:\Users\fuckheinerkleinehack\Documents\RZGS2\RZGCS\Python\backend\mavlink_connector.py)</error></testcase></testsuite></testsuites>